app/Http/Controllers/DaftarBarangController.php, app/Http/Controllers/HasilPemeriksaanController.php, app/Models/CheckUpResult.php, app/Models/DetailItemInPatient.php, app/Models/DetailServiceInPatient.php, database/migrations/2021_01_29_143111_create_detail_item_in_patients_table.php, database/migrations/2021_01_29_143146_create_detail_service_in_patients_table.php, database/seeds/DataDummySeeder.php
…tory Item Movement on Ubah Daftar Barang
=> add Create and Detail Hasil Pemeriksaan dengan Rawat Inap and Add History Item Movement and add DB Seeder

public/main/js/hasil-pemeriksaan/detail-hasil-pemeriksaan.js, public/main/js/pasien/riwayat-pasien.js
=> add selling price in detail hasil pemeriksaan and detail riwayat pemeriksaan

app/Http/Controllers/HasilPemeriksaanController.php, app/Models/TempCountItem.php, database/migrations/2021_04_01_160537_create_temp_count_items_table.php
=> add Validation Stock Total and Duplicate Medicine Group Hasil Pemeriksaan

app/Http/Controllers/LaporanKeuanganHarianController.php, app/Http/Controllers/PembayaranController.php, database/seeds/DataDummySeeder.php
=> Fixing API Drop Down Pembayaran and Add Filter on Index Laporan Keuangan Harian

public/main/css/global.css, public/main/js/hasil-pemeriksaan/form-hasil-pemeriksaan.js, public/main/js/hasil-pemeriksaan/kelompok-obat.js
=> add disabled effect for btn delete and input for qty in hasil pemeriksaan

app/Http/Controllers/DaftarBarangController.php, app/Http/Controllers/DaftarJasaController.php, app/Http/Controllers/HargaBarangController.php, app/Http/Controllers/HargaJasaController.php, app/Http/Controllers/HasilPemeriksaanController.php, app/Http/Controllers/KategoriBarangController.php, app/Http/Controllers/KategoriJasaController.php, app/Http/Controllers/PasienController.php, app/Http/Controllers/RegistrasiController.php, public/main/js/user/user.js, resources/views/user/modal-user.blade.php
Remove comment, add access role in Module Gudang and Layanan, change drop down name in user registration
=> Add New Changes

app/Http/Controllers/HasilPemeriksaanController.php, app/Http/Controllers/RegistrasiController.php, app/Http/Controllers/UserController.php
- List Dokter
- Soft delete Hasil Pemeriksaan
- Validasi Simpan Gambar Hasil Pemeriksaan
- Delete Pendaftaran Berobat Admin Only
- Create Hasil Pemeriksaan Bugs
=> Fixing Bugs

app/Exports/DataLaporanKeuanganBulanan.php, app/Exports/DataLaporanKeuanganMingguan.php, app/Exports/DataPasien.php, app/Http/Controllers/LaporanKeuanganBulananController.php, app/Http/Controllers/LaporanKeuanganHarianController.php, app/Http/Controllers/LaporanKeuanganMingguanController.php, config/database.php, routes/api.php
Other fixing:
- Change config/database.php
- Fixing Route Download Excel Laporan Keuangan Bulanan
=> Fixing Laporan Keuangan Harian, Mingguan, Bulanan

public/main/js/hasil-pemeriksaan/form-hasil-pemeriksaan.js
change medicine_group_id to id
=> fix bug hasil pemeriksaan

public/main/js/pembayaran/pembayaran-tambah.js, resources/views/pembayaran/pembayaran-tambah.blade.php
=> fix create pembayaran

public/main/js/pembayaran/pembayaran-edit.js, public/main/js/pembayaran/pembayaran-tambah.js, resources/views/pembayaran/pembayaran-edit.blade.php
add quantitiy on param barang (item)
=> updated pembayaran create and edit

app/Http/Controllers/PembayaranController.php, app/Models/ListofPaymentItem.php, database/migrations/2021_07_26_213622_add_detail_medicine_group_check_up_result_id_in_list_of_payment_items.php
- Fixing Cancel Payment and Print Result
=> Fixing and Update Hasil Pemeriksaan

app/Http/Controllers/HasilPemeriksaanController.php, app/Http/Controllers/PasienController.php, app/Http/Controllers/PembayaranController.php, database/seeds/DataDummySeeder.php, resources/views/layout/master.blade.php
- Fixing Hasil Pemeriksaan
- Fixing History Data Patient
- Fixing Menu Pembayaran
- Change Footer Content
- Adding Data Dummy
=> Update Several Menus

app/Exports/DataLaporanKeuanganBulanan.php, app/Exports/DataLaporanKeuanganMingguan.php, app/Exports/DataPasien.php, app/Http/Controllers/HasilPemeriksaanController.php, app/Http/Controllers/LaporanKeuanganBulananController.php, app/Http/Controllers/LaporanKeuanganHarianController.php, app/Http/Controllers/LaporanKeuanganMingguanController.php, app/Http/Controllers/PembayaranController.php, app/Models/ListofPaymentItem.php, app/Models/list_of_payment_medicine_groups.php, database/migrations/2021_07_28_122325_create_list_of_payment_medicine_groups_table.php, database/migrations/2021_07_28_122858_edit_column_list_of_payment_items.php
- Change Flow Data Payment
- Adjustment Laporan Keuangan with new flow
- Adjustment Pembayaran with new flow
=> Add New Changes Back End

app/Exports/DataLaporanKeuanganBulanan.php, app/Exports/DataLaporanKeuanganMingguan.php, app/Exports/DataPasien.php, app/Http/Controllers/LaporanKeuanganBulananController.php, app/Http/Controllers/LaporanKeuanganHarianController.php, app/Http/Controllers/LaporanKeuanganMingguanController.php
- Make Index Payment into Price Group
=> Change Laporan Keuangan

app/Http/Controllers/DashboardController.php, app/Http/Controllers/HasilPemeriksaanController.php, app/Http/Controllers/LaporanKeuanganBulananController.php, app/Http/Controllers/LaporanKeuanganHarianController.php, app/Http/Controllers/LaporanKeuanganMingguanController.php, app/Http/Controllers/PembayaranController.php, public/main/js/laporan-keuangan/bulanan/bulanan.js, public/main/js/laporan-keuangan/bulanan/detail-bulanan.js, public/main/js/laporan-keuangan/harian/detail-harian.js, public/main/js/laporan-keuangan/harian/harian.js, public/main/js/laporan-keuangan/mingguan/detail-mingguan.js, public/main/js/laporan-keuangan/mingguan/mingguan.js, public/main/js/master.js, public/main/js/pembayaran/pembayaran-detail.js, public/main/js/pembayaran/pembayaran-edit.js, public/main/js/pembayaran/pembayaran-tambah.js, public/main/js/pembayaran/pembayaran.js
- Filter data role dokter hanya cabangnya sendiri
=> Add Role Doctor to Pembayaran and Laporan Keuangan

public/main/js/dokter/penerimaan-pasien/penerimaan-pasien.js, public/main/js/hasil-pemeriksaan/hasil-pemeriksaan.js, public/main/js/laporan-keuangan/bulanan/bulanan.js, public/main/js/laporan-keuangan/harian/harian.js, public/main/js/laporan-keuangan/mingguan/mingguan.js, public/main/js/pasien/pasien.js, public/main/js/pembayaran/pembayaran.js, public/main/js/pendaftaran/pendaftaran-pasien/pendaftaran-pasien.js, resources/views/dokter/penerimaan-pasien/index.blade.php, resources/views/hasil-pemeriksaan/index.blade.php, resources/views/laporan-keuangan.blade.php, resources/views/laporan-keuangan/bulanan/index.blade.php, resources/views/laporan-keuangan/harian/index.blade.php, resources/views/laporan-keuangan/mingguan/index.blade.php, resources/views/pasien/index.blade.php, resources/views/pembayaran/index.blade.php, resources/views/pendaftaran/pendaftaran-pasien/index.blade.php
- Change Index Menu
- Change Result Excel Laporan Keuangan
=> Change Several Menu

app/Http/Controllers/HasilPemeriksaanController.php, public/main/css/global.css, public/main/js/hasil-pemeriksaan/detail-hasil-pemeriksaan.js, public/main/js/hasil-pemeriksaan/form-hasil-pemeriksaan.js, public/main/js/hasil-pemeriksaan/hasil-pemeriksaan.js, public/main/js/hasil-pemeriksaan/kelompok-obat.js
add field quantity on kelompok obat hasil pemeriksaan
=> Development hasil pemeriksaan

app/Http/Controllers/DaftarBarangController.php, app/Http/Controllers/DaftarJasaController.php, app/Http/Controllers/DaftarMetodePembayaranController.php, app/Http/Controllers/HargaJasaController.php, app/Http/Controllers/HargaKelompokObatController.php, app/Http/Controllers/HasilPemeriksaanController.php, app/Http/Controllers/KelompokObatController.php, app/Http/Controllers/PembayaranController.php, app/Models/ListofPaymentService.php, app/Models/list_of_payment_medicine_groups.php, composer.lock, database/migrations/2022_01_23_113654_add_discount_and_method_payment_in_payments.php
- Paging Daftar barang
- Paging Harga jasa
- Paging Kelompok Obat
- Paging Pembayaran
- Update Pembayaran with Payment Method and Discount
=> Add several API

public/main/js/gudang/daftar-barang/daftar-barang.js, public/main/js/gudang/kelompok-obat/kelompok-obat.js, public/main/js/layanan/pembagian-harga/harga-jasa.js, resources/views/gudang/daftar-barang/index.blade.php, resources/views/gudang/kelompok-obat/index.blade.php, resources/views/layanan/pembagian-harga/index.blade.php
- daftar barang
- kelompok obat
- harga jasa
=> update pagination on index

app/Http/Controllers/PembayaranController.php, resources/views/pdf.blade.php
- Fitur Update Pembayaran
- Print Struk dengan diskon
=> Deployment API

app/Console/Commands/UpdateExpiredDate.php, app/Console/Kernel.php, app/Exports/DaftarBarang.php, app/Exports/DataRekapDaftarBarang.php, app/Http/Controllers/DaftarBarangController.php, app/Http/Controllers/HargaBarangController.php, app/Http/Controllers/HargaKelompokObatController.php, app/Http/Controllers/HasilPemeriksaanController.php, app/Http/Controllers/KategoriBarangController.php, app/Http/Controllers/KelompokObatController.php, app/Http/Controllers/SatuanBarangController.php, app/Imports/DaftarBarangImport.php, app/Imports/MultipleSheetImportDaftarBarang.php, app/Models/ListofItems.php, database/migrations/2022_05_31_070740_add_expired_date_and_limit_item.php
- add feature limit barang and tanggal kedaluwarsa
=> Remove Soft Delete Item and Add new feature on Daftar Barang

app/Http/Controllers/PengeluaranController.php, app/Http/Controllers/UserController.php, public/main/js/master.js, public/main/js/pengeluaran/pengeluaran.js, resources/views/pengeluaran/modal-pengeluaran.blade.php
- Error Pengeluaran
- Add Dokter and Resepsionis in pengeluaran
=> Fixing Pengeluaran

app/Exports/DataDaftarBarangPetShop.php, app/Exports/DataHargaPetShop.php, app/Exports/MultipleSheetUploadHargaBarangPetShop.php, app/Http/Controllers/DaftarBarangPetshopController.php, app/Http/Controllers/HargaBarangPetShopController.php, app/Http/Controllers/PembayaranPetShopController.php, app/Http/Controllers/PengeluaranController.php, app/Http/Controllers/PenggajianController.php, app/Imports/DaftarBarangImport.php, app/Imports/DaftarBarangImportPetShop.php, app/Imports/HargaBarangPetShopImport.php, app/Imports/MultipleSheetImportHargaBarangPetShop.php, app/Models/master_payment_petshop.php, app/Models/payment_petshop.php, database/migrations/2022_10_09_181511_create_master_payment_petshops_table.php, database/migrations/2022_10_09_181641_create_payment_petshops_table.php, public/main/css/pengeluaran.css, public/main/css/penggajian.css, public/main/js/gudang/pembagian-harga-petshop/harga-barang-petshop.js, public/main/js/pembayaran/pembayaran.js, public/main/js/pengeluaran/pengeluaran.js, public/main/js/penggajian/penggajian.js, resources/views/pembayaran/pembayaran-petshop-tambah.blade.php, resources/views/pengeluaran/index.blade.php, resources/views/penggajian/index.blade.php, resources/views/petshop-print.blade.php, routes/api.php, routes/web.php
- Filter Penggajian
- FIlter Pengeluaran
- Pembayaran Pet Shop
- Add Data Pet Shop
=> Enhancement Feature

app/Http/Controllers/HasilPemeriksaanController.php, app/Http/Controllers/PembayaranController.php, app/Http/Controllers/PembayaranPetShopController.php, app/Models/payment_petshop_with_clinic.php, database/migrations/2022_10_20_042411_create_payment_petshop_with_clinics_table.php, public/main/js/pembayaran/pembayaran-detail.js, public/main/js/pembayaran/pembayaran-tambah.js, public/main/js/pembayaran/pembayaran.js, resources/views/layout/modal-confirmation-pet-shop.blade.php, resources/views/pdf.blade.php, resources/views/pembayaran/index.blade.php, resources/views/pembayaran/pembayaran-detail.blade.php, resources/views/pembayaran/pembayaran-tambah.blade.php, routes/api.php
- integrated nota result payment with pet shop item
- adjustment endpoint payment pet shop
=> Fixing Several Feature

app/Http/Controllers/DaftarBarangPetshopController.php, app/Http/Controllers/HargaBarangPetShopController.php, app/Http/Controllers/PembayaranPetShopController.php, public/main/css/pembayaran.css, public/main/js/pembayaran/pembayaran.js, resources/views/pembayaran/index.blade.php
- Search on Pembayaran Pet Shop
- update item pet shop
=> Fixing Issue
